- name: add code apt signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: add code source repository into sources list
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: code

- name: install code package
  apt:
    name: code