- name: add docker apt signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker source repository into sources list
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker

- name: install docker package
  apt:
    name: docker-ce