- name: install system packages
  apt:
    name:
      - openssh-server
      - vim
      - htop
      - screen
      - tree
      - iotop
      - git
      - rsync
      - curl
      - net-tools
      - nmap
      - traceroute
      - apache2

- name: install gimp
  apt:
    name: gimp

- name: install inkscape
  apt:
    name: inkscape

- name: install pavucontrol
  apt:
    name: pavucontrol

- name: install audacity
  apt:
    name: audacity